Generate Docker offline image

diff --git a/.github/workflows/build-openwer-docker-image.yml b/.github/workflows/build-openwer-docker-image.yml
--- a/.github/workflows/build-openwer-docker-image.yml
+++ b/.github/workflows/build-openwer-docker-image.yml
@@ -47,39 +47,60 @@ jobs:
         id: down
         if: (!cancelled())
         run: |
-          # Retrieve the latest OpenWrt rootfs file from releases
+          # Determine the OpenWrt source code repository
+          if [[ "${{ inputs.source_branch }}" =~ ^openwrt ]]; then
+              REPO_URL="https://github.com/openwrt/openwrt"
+          elif [[ "${{ inputs.source_branch }}" =~ ^lede ]]; then
+              REPO_URL="https://github.com/coolsnowwolf/lede"
+          elif [[ "${{ inputs.source_branch }}" =~ ^immortalwrt ]]; then
+              REPO_URL="https://github.com/immortalwrt/immortalwrt"
+          else
+              echo "Error: Unknown source code repository."
+              exit 1
+          fi
+          source_branch_input="${{ inputs.source_branch }}"
+          REPO_NAME="${source_branch_input%_*}"
+          REPO_BRANCH="${source_branch_input##*_}"
+
+          # Query the latest release asset via GitHub API
           latest_version=$(curl -s \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/releases?per_page=20 | \
-              jq -r --arg RTK "OpenWrt_${{ inputs.source_branch }}_save_" \
-              --arg BOARD "rootfs" \
-              '[.[] | select(.tag_name | contains($RTK))] |
-              map(.assets[] | select(.name | contains($BOARD) and endswith(".tar.gz"))) |
-              sort_by(.updated_at) |
+              jq -r --arg RTK "OpenWrt_${{ inputs.source_branch }}_" \
+              --arg BOARD "-rootfs.tar.gz" \
+              '[.[] | select(.tag_name | contains($RTK)) |
+              {tag: .tag_name} + (.assets[] | select(.name | endswith($BOARD)) |
+              {data: .updated_at, url: .url, name: .name})] |
+              sort_by(.data) |
               reverse |
-              .[0] |
-              {data: .updated_at, url: .url, name: .name}')
+              .[0]')
 
           [[ -z "${latest_version}" || "${latest_version}" == "null" ]] && {
               echo "Error: Failed to resolve OpenWrt rootfs download URL."
               exit 1
           }
 
-          # Extract download URL and filename
+          # Extract download URL, filename, and release tag
           latest_url="$(echo ${latest_version} | jq -r '.url')"
           openwrt_filename="$(echo ${latest_version} | jq -r '.name')"
+          release_tag="$(echo ${latest_version} | jq -r '.tag')"
+          echo "Matched release tag: ${release_tag}"
+          echo "build_tag=${release_tag}" >> ${GITHUB_OUTPUT}
 
           # Download asset via GitHub API (binary stream)
-          echo "Downloading: ${openwrt_filename}"
           [[ -d "openwrt" ]] || mkdir -p openwrt
+          echo "Downloading: ${openwrt_filename}"
           curl -fsSL \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/octet-stream" \
                "${latest_url}" \
                -o "openwrt/${openwrt_filename}"
           [[ "${?}" -ne "0" ]] && echo "Error: Download failed." && exit 1
-
+          df -hT ${PWD}
+          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
+          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
+          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Build the Docker image
@@ -87,8 +108,35 @@ jobs:
         if: ${{ steps.down.outputs.status == 'success' && !cancelled() }}
         run: |
           chmod +x ${MAKE_DOCKER_SH}
-          ${MAKE_DOCKER_SH}
+          ${MAKE_DOCKER_SH} ${{ inputs.source_branch }}
+
           echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Upload packaged OpenWrt to Release
+        uses: ncipollo/release-action@main
+        if: ${{ steps.make.outputs.status == 'success' && !cancelled() }}
+        with:
+          tag: ${{ steps.down.outputs.build_tag }}
+          artifacts: offline/*.tar.gz
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          makeLatest: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body: |
+            ### OpenWrt Image Information
+            - Default IP: `192.168.1.1`
+            - Default username: `root`
+            - Default password: `password`
+            - Default WIFI name: `OpenWrt`
+            - Default WIFI password: `none`
+            ### Install to EMMC
+            - Login to OpenWrt → `System` → `Amlogic Service` → `Install OpenWrt`
+            ### OpenWrt source code
+            - [${{ env.REPO_NAME }}](${{ env.REPO_URL }}/tree/${{ env.REPO_BRANCH }})
+            ### Applicable Platform
+            - 🐧 `arm64`
+            - 🐋 Docker image: https://hub.docker.com/u/ophub
 
       - name: Set up QEMU
         id: qemu
